#!/bin/bash
# In ingresso vuole gli url dei due repository: il primo è il vecchio, il secondo è il nuovo

OLDURL=$1
NEWURL=$2
echo oldurl: $OLDURL
echo newurl: $NEWURL

git clone --mirror $OLDURL
cd $2.git
git remote add gitlab $NEWURL
git -c http.sslVerify=false push gitlab --mirror
